extend type Query {
  getOrder(id: ID!): Order
  listOrders: [Order!]!
  listCustomerOrders(customerId: ID!): [Order!]!
}

input CheckoutInput {
  shippingAddressId: String
  billingAddressId: String
  shippingAddress: CreateAddressInput
  billingAddress: CreateAddressInput
  paymentMethod: String
  paymentDetails: Map
  shippingCarrier: String
  shippingMethod: String
}

extend type Mutation {
  createOrderFromCart(cartId: ID!, input: CheckoutInput): Order!
}

type Order {
  id: ID!
  customerId: String!
  status: String!
  totalPrice: Float!
  items: [OrderItem!]!
  shippingAddressId: String
  billingAddressId: String
  shippingAddressJson: String
  billingAddressJson: String
  paymentMethod: String
  shippingCarrier: String
  shippingMethod: String
}

type OrderItem {
  id: ID!
  productId: String!
  quantity: Int!
  unitPrice: Float!
}
